### ISSUE TITLE
和E-Hentai Downloader脚本冲突

### ISSUE THREAD

**Issue by ssbroad** [cpuopt/Ehentai-gallery-script#1]
https://sleazyfork.org/en/scripts/10379-e-hentai-downloader
当画廊不存在种子时，2个脚本都可以正常使用。
当画廊存在种子时，启用本脚本，则E-Hentai Downloader无法正常弹出下载

**Comment by cpuopt** [comment]
实测问题没法复现
https://cd.xfan.top/s/GJuK

**Comment by ssbroad** [comment]
奇了怪了，测试篡改猴或暴力猴都是如此。
暴力猴启用E-Hentai Downloader后，本脚本直接不显示了，但E-Hentai Downloader正常使用。
篡改猴可以正常显示，但E-Hentai Downloader在种子画廊又不弹出下载了。
总之2个脚本管理器在处理2个脚本共存时都或多或少有点问题。
chrome 121.0.6167.162, 关闭其他所有扩展和脚本后测试问题仍在。不知道问题出在哪

**Comment by cpuopt** [comment]
可以打开控制台录个视频看看
理论上不存在冲突的功能

**Comment by ssbroad** [comment]
在E-Hentai Downloader弹出存在种子警告后，点击确认，无任何反应
控制台显示错误：
userscript.html?name=E-Hentai-Downloader.user.js&id=4a69f0a9-8b2f-4d33-8365-299fa6b59bc4:14041 
Uncaught TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at userscript.html?name=E-Hentai-Downloader.user.js&id=4a69f0a9-8b2f-4d33-8365-299fa6b59bc4:14041:22
    at NodeList.forEach (<anonymous>)
    at initEHDownload (userscript.html?name=E-Hentai-Downloader.user.js&id=4a69f0a9-8b2f-4d33-8365-299fa6b59bc4:14037:27)
    at HTMLDivElement.<anonymous> (userscript.html?name=E-Hentai-Downloader.user.js&id=4a69f0a9-8b2f-4d33-8365-299fa6b59bc4:14956:2)

禁用本脚本后，就正常下载了。

**Comment by cpuopt** [comment]
与你的报错相同：
https://github.com/ccloli/E-Hentai-Downloader/issues/183

调整脚本执行顺序的方法：
https://github.com/ccloli/E-Hentai-Downloader/issues/50
E-Hentai-Downloader那边有很多这个报错的问题

我这边Tampermonkey顺序怎么放都不影响。
