### ISSUE TITLE
能顺便显示收藏备注吗

### ISSUE THREAD

**Issue by ssbroad** [cpuopt/Ehentai-gallery-script#2]
看不懂js，如果能在脚本功能区域显示收藏备注就好了，现在想看收藏备注还是得打开收藏弹窗.
这个脚本太方便了，厚颜无耻地想更方便

**Comment by cpuopt** [comment]
https://github.com/cpuopt/Ehentai-gallery-script/commit/35a936d76d9b8d1d15cfa3d8cbef65f055c974e2
已改进，更新到最新版即可

**Comment by ssbroad** [comment]
> [35a936d](https://github.com/cpuopt/Ehentai-gallery-script/commit/35a936d76d9b8d1d15cfa3d8cbef65f055c974e2) 已改进，更新到最新版即可

牛的，完美了
